apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_USER: dXNlcg==              # base64("user")
  DB_PASSWORD: cGFzc3dvcmQ=      # base64("password")
  DB_NAME: MTc3OXByb2plY3RkYg==  # base64("1779projectdb")
  DB_PORT: NTQzMg==              # base64("5432")
  MAILTRAP_USER: MjJjMDNmMWFhN2Y0YTU=
  MAILTRAP_PASS: ZWUyNTc2MmNiNjYwYWE=
  JWT_SECRET: ZWNlMTc3OWp3dA==
  

